### ISSUE TITLE
will it work with HTTP POST method

### ISSUE THREAD

**Issue by xmlking** [rjlopezdev/typeorm-express-query-builder#2]
for security reasons I would like to use POST method.  wonder if this works?

**Comment by rjlopezdev** [comment]
Hi! Thanks for your interest :)
I don't try this, but QueryBuilder uses req.query parsed by Express.
You can try passing your query as the following format:
Instead of
`GET ?foo__contains=value&role__in=admin,common&page=1`
do that:
```javascript
POST 
{
  "foo__contains": "value",
  "role__in": "admin,common",
  "page": 1
}
```
I will improve doc. comming soon :)
