### ISSUE TITLE
Select fields

### ISSUE THREAD

**Issue by FilippiSilva** [rjlopezdev/typeorm-express-query-builder#214]
Hello, it would be interesting to have a parameter to select the fields of the entity.

This helps in the frontend to list the entity in selectors.

Congratulations on the library, it is very useful!

**Comment by rjlopezdev** [comment]
Hi @FilippiSilva sorry for delay, so busy! 🙏🏻 
Looks interesting, I will add this feature next week :)

Thanks for your suggestion!

**Comment by rjlopezdev** [comment]
Close in favour of #254 
Released at `v1.4.0`
