### ISSUE TITLE
How to use where or

### ISSUE THREAD

**Issue by cnly1987** [rjlopezdev/typeorm-express-query-builder#257]
How to use where or,
```
{
  where:[{name:v}, {text:v}]
}
```

**Comment by rjlopezdev** [comment]
Hi @cnly1987, Unfortunately this library does not support `OR` feature.
Maybe I will add possibility to use complex predicates in the future.

**Comment by cnly1987** [comment]
> Hi @cnly1987, Unfortunately this library does not support `OR` feature. Maybe I will add possibility to use complex predicates in the future.

thanks! 
Very good project, there are many problems with typeorm's find option, it would be better if it is implemented by querybuild.
