### ISSUE TITLE
Problem to install with yarn 

### ISSUE THREAD

**Issue by Wesleyss071299** [rjlopezdev/typeorm-express-query-builder#278]
error /home/wesley/Desktop/webScrap/node_modules/typeorm-express-query-builder: Command failed.
Exit code: 127
Command: tsc --outDir ./dist
Arguments: 
Directory: /home/wesley/Desktop/webScrap/node_modules/typeorm-express-query-builder

**Comment by rjlopezdev** [comment]
Hi @Wesleyss071299 do you refer to dependency install or project install?
Which command did you run?

**Comment by FilippiSilva** [comment]
I'm having the same problem installing the dependency on my project. I believe it is the script "postinstall" that makes the build after installing the dependency. Would it be possible to provide the lib already transpiled?

I believe that would solve the problem.

**Comment by rjlopezdev** [comment]
Fixed at `v1.5.1`
