### ISSUE TITLE
Filtering by date between

### ISSUE THREAD

**Issue by vladimirantos** [rjlopezdev/typeorm-express-query-builder#392]
Hey,
filtering by a range of two dates isn't working. I have a column 'date' in my database and I would like to create a SQL query `select * from table where date between '2022-09-01` and '2022-09-30''. In the URL I have this: `?date__between=2022-09-01, 2022-09-30` but when I look in the TypeORM log, it generates this query: `WHERE (`date` BETWEEN ? AND ?)  -- PARAMETERS: [null,null]` and error 
**Unknown column 'NaN' in 'where clause'**.
 How to filter with between two dates? Thanks

**Comment by rjlopezdev** [comment]
Hi @vladimirantos 
Currently is not supported, but I will add it
Thanks for your suggestion ❤️

**Comment by rjlopezdev** [comment]
Hi @vladimirantos 
Date filtering is now supported since `v1.7.0`
Thanks for your suggestion!

**Comment by vladimirantos** [comment]
@rjlopezdev Good job, I'll try it. Thank you
