### ISSUE TITLE
Refactor: set query in `build` method intead of `constructor`

### ISSUE THREAD

**Issue by rjlopezdev** [rjlopezdev/typeorm-express-query-builder#4]
In order to reuse `QueryBuilder` instance.

**BREAKING CHANGE.**

**Comment by rgolea** [comment]
Hi there @rjlopezdev! Can we make this available for mongoose? Tell me how can I help.

**Comment by rjlopezdev** [comment]
Hi @rgolea ! Please, opene a new issue explaning the expected behavior 🙏

**Comment by rgolea** [comment]
@rjlopezdev done! Check #7
