### ISSUE TITLE
[Question] How to not set a limit

### ISSUE THREAD

**Issue by matiasmir** [rjlopezdev/typeorm-express-query-builder#92]
Hi, I have an endpoint that sometimes requires to be paginated and sometimes not, those times when we don't send the limit param on the url it gets set to 25 by default, so my question is: how can we set that parameter to infinite or something like that? I know that we could set a big number by default on those request but I don't like that idea since it doesn't seem to be a escalable solution at all, any ideas? thanks!

**Comment by rjlopezdev** [comment]
Hi @matiasmir

Currently, there is no an available option to disable pagination.

Btw, I'm interested on this feature and I'll add it ASAP.

Thanks for your suggestion and report!

**Comment by rjlopezdev** [comment]
@matiasmir released on #95 v1.2.0

Feel free to report new bugs and features :)
